### PR TITLE
A few changes seem to be needed for GCC compatibility

### PR DESCRIPTION
**Pull request by dok-net**
On the versions of GCC that I tried, there are a few incompatilities. I'm more than willing to adapt my choices, if this PR gets review.

### CODE REVIEW

**Comment by dok-net** [comment]
@microsoft-github-policy-service agree

**Comment by davidmatson** [comment]
Thanks for trying this out on GCC and contributing these fixes!

**Comment by davidmatson** [comment]
@dok-net @kaartee I think most of this is covered now that #10 and #12 are merged. This PR has been open for awhile, and I'd like to resolve so we don't leave it indefinitely.

I believe the remaining parts here are:
* Switching from task to ::async::task in a couple of places where GCC resolves names differently than MSVC does.
* Considering adding support when compiling without exceptions enabled.

Are you interested in moving forward with either of those parts?

I'm happy to take the first change (task => ::async::task), if you'd like to do that in this PR.
For the second change (support when exceptions disabled), I'd like to consider that in a separate PR.

**Comment by dok-net** [comment]
> Are you interested in moving forward with either of those parts?

::async::task is done.

Do I understand correctly that you will fix the no-exeptions issue?

**Comment by davidmatson** [comment]
@dok-net 
Thanks for finishing the ::async::Task part!
Let's open a separate issue for no-exceptions. I'd like to understand the scenario more, and consider some details such as whether this should be enabled for all files, or if there are some cases where it doesn't make sense (such as async::to_future, if std::future inherently uses exceptions such as std::future_error).

**Pull request merged**
